name: Intermediate
on:
  workflow_call:

jobs:
  call_release:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.get_release.outputs.release }}
    steps:
      - name: Call release workflow
        id: get_release
        uses: elBotija/workflows/.github/workflows/a.yml@main
        with:
          version: "v2.0.0"