name: Final
on:
  push:
    branches:
      - main

jobs:
  get_release_job:  # Nombre del job
    runs-on: ubuntu-latest
    uses: ./.github/workflows/b.yml  

  process_release_job:  # Segundo job
    runs-on: ubuntu-latest
    needs: get_release_job  # Referencia al nombre del job anterior
    steps:
      - name: Access release variable
        run: echo "Release version is ${{ needs.get_release_job.outputs.release }}"  # Referencia al output del job anterior