name: Final
on:
  push:
    branches:
      - main

jobs:
  get_release_job:
    runs-on: ubuntu-latest
    uses: elbotija/workflows/.github/workflows/b.yml@main  # Se referencia correctamente el workflow reutilizable

  process_release_job:
    runs-on: ubuntu-latest
    needs: get_release_job  # Dependencia del job anterior
    steps:
      - name: Access release variable
        run: echo "Release version is ${{ needs.get_release_job.outputs.release }}"  # Accede al output del job anterior